# Generated by Django 4.0.3 on 2022-03-05 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labeling_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="misconception",
            name="list_position",
            field=models.IntegerField(null=True),
        ),
    ]
